### ISSUE TITLE
Add id and class attributes for nav section

### ISSUE THREAD

**Issue by gregthompson27** [CharlesJustus/CharlesJustus.github.io#2]
<h3>Feedback for todo 10</h3>

https://github.com/CharlesJustus/CharlesJustus.github.io/blob/b9c51da6a99e545b3772637b3e38e12d9f3bc652/index.html#L13-L23

@CharlesJustus, Make sure to add the style rules listed in [TODO 10 Part 2](https://github.com/OperationSpark/first-website-hs#part-2-the-nav-section) at the bottom of your `style.css` file.

You did a good job of this for the rest of the TODOs, but the code you added for the first issue I left for you has some `id` and `class` attributes that need to be added

**Comment by JoshHunter11** [comment]
@gregthompson27 issue resolved
